# Generated by Django 4.2.5 on 2023-09-06 13:01

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Writing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('main_genre', models.CharField(choices=[('Action and Adventure', 'Action and Adventure'), ('Comedy', 'Comedy'), ('Crime and Mistery', 'Crime and Mistery'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('SciFi', 'SciFi'), ('Romance', 'Romance'), ('Poetry', 'Poetry'), ('Other', 'Other')], max_length=20)),
                ('sub_genre', models.CharField(blank=True, choices=[('Action and Adventure', 'Action and Adventure'), ('Comedy', 'Comedy'), ('Crime and Mistery', 'Crime and Mistery'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('SciFi', 'SciFi'), ('Romance', 'Romance'), ('Poetry', 'Poetry'), ('Other', 'Other')], max_length=20)),
                ('content', models.TextField()),
                ('featured_image', cloudinary.models.CloudinaryField(default='placeholder', max_length=255, verbose_name='image')),
                ('abstract', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='writings', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='writing_likes', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Draft'), (1, 'Publish')], default=0)),
                ('comment_type', models.IntegerField(choices=[(0, 'Comment'), (1, 'Writing')], default=0)),
                ('approved_comment', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('likes', models.ManyToManyField(blank=True, related_name='comment_likes', to=settings.AUTH_USER_MODEL)),
                ('writing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='thewcwebpage.writing')),
            ],
            options={
                'ordering': ['-created_on'],
            },
        ),
    ]
