# Generated by Django 4.2.5 on 2023-09-21 22:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('thewcwebpage', '0002_writing_approved_writing'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Action and Adventure', 'Action and Adventure'), ('Comedy', 'Comedy'), ('Crime and Mistery', 'Crime and Mistery'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('SciFi', 'SciFi'), ('Romance', 'Romance'), ('Poetry', 'Poetry'), ('Other', 'Other')], max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='writing',
            name='main_genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='main_genre', to='thewcwebpage.genre'),
        ),
        migrations.AlterField(
            model_name='writing',
            name='sub_genre',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sub_genre', to='thewcwebpage.genre'),
        ),
    ]
