# Generated by Django 4.2.5 on 2023-09-21 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewcwebpage', '0003_genre_alter_writing_main_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='name',
            field=models.CharField(choices=[('Action and Adventure', 'Action and Adventure'), ('Comedy', 'Comedy'), ('Crime and Mistery', 'Crime and Mistery'), ('Fantasy', 'Fantasy'), ('Horror', 'Horror'), ('SciFi', 'SciFi'), ('Romance', 'Romance'), ('Poetry', 'Poetry'), ('Other', 'Other')], default='Other', max_length=20),
        ),
    ]
