# Generated by Django 4.2.5 on 2023-09-26 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thewcwebpage', '0004_alter_genre_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
